/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Dashboard/Dashboard` | `/Dashboard/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Dashboard/Room` | `/Dashboard/Room`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/Dashboard/Dashboard` | `/Dashboard/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/Dashboard/Room` | `/Dashboard/Room`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/Dashboard/Dashboard${`?${string}` | `#${string}` | ''}` | `/Dashboard/Dashboard${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/Dashboard/Room${`?${string}` | `#${string}` | ''}` | `/Dashboard/Room${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Dashboard/Dashboard` | `/Dashboard/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Dashboard/Room` | `/Dashboard/Room`; params?: Router.UnknownInputParams; };
    }
  }
}
